//天気コードと対応するテキスト
export const weatherDescriptions: { [key: number]: string } = {
  0: "Clear",
  1: "Mostly Clear",
  2: "Cloudy",
  3: "Partly Cloudy",
  45: "Fog",
  48: "Frost",
  51: "Light Rain",
  53: "Moderate Rain",
  56: "Light Snow",
  57: "Moderate Snow",
  61: "Light Thunderstorm",
  63: "Moderate Thunderstorm",
  65: "Severe Thunderstorm",
  66: "Light Thunder Snow",
  67: "Moderate Thunder Snow",
  71: "Light Rain or Snow",
  73: "Moderate Rain or Snow",
  75: "Heavy Rain or Snow",
  77: "Hail",
  80: "Light Thunder",
  81: "Moderate Thunder",
  82: "Severe Thunder",
  85: "Light Snow or Hail",
  86: "Moderate Snow or Hail",
  95: "Severe Thunderstorm",
};
